apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp1
        sel: hello
    spec:
      containers:
      - name: myapp1
        image: docker.io/pintulohargcetts/nginx_custom:v3
        ports:
        - containerPort: 80
