apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argocd-apps/meetus-ifland/my-apps-2 # it watches over the apps directory
    repoURL: https://github.com/pintulohargcetts/argocd-application-example.git # always put the .git extension here
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: beta # meetus-qa
  syncPolicy:
    syncOptions:
    - CreateNamespace=true # create if not exists . 
    automated: 
      selfHeal: false
      prune: false
