apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-apps-3
  namespace: argocd
spec:
  project: default
  source:
    path: my-apps/apps-3
    repoURL: 'https://github.com/pintulohargcetts/argocd-application-example.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: beta
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true