apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp2
        sel: hello
    spec:
      containers:
      - name: myapp2
        image: docker.io/pintulohargcetts/nginx_custom:v3
        ports:
        - containerPort: 80
